"""
Report Builder
==============
Generates structured JSON and Markdown reports from pipeline output.
Markdown format is designed to render cleanly on GitHub.
"""

import json
import datetime


def build_json_report(payload: dict, output_path: str) -> None:
    """Save full pipeline payload as pretty-printed JSON."""
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)


def build_markdown_report(payload: dict, output_path: str) -> None:
    """
    Generate a GitHub-friendly Markdown report.
    Includes: metadata, transcription, quality metrics table, flagged segments.
    """
    t = payload.get("transcription", {})
    q = payload.get("quality_analysis", {})
    tr = payload.get("translation", {})

    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    wer_line = f"{q['wer']:.2%}" if q.get("wer") is not None else "N/A (no reference provided)"
    cer_line = f"{q['cer']:.2%}" if q.get("cer") is not None else "N/A"
    wer_grade = q.get("wer_grade", "—")

    md = f"""# 🎙️ ASR Pipeline Report

> **Generated:** {now}  
> **Pipeline Version:** {payload.get("pipeline_version", "1.0.0")}

---

## 📋 Audio Metadata

| Field | Value |
|-------|-------|
| File | `{t.get("audio_file", "—")}` |
| Language | {t.get("language_name", "—")} (`{t.get("detected_language", "—")}`) |
| Script | {t.get("script", "—")} |
| Whisper Model | `{t.get("model_used", "—")}` |
| Total Segments | {t.get("total_segments", 0)} |
| Processing Time | {t.get("transcription_time_sec", "—")}s |

---

## 📝 Transcription

```
{t.get("full_text", "[No transcription available]")}
```

---

## 🌐 Translation

| Field | Value |
|-------|-------|
| Source Language | `{tr.get("source_language", "—")}` |
| Target Language | `{tr.get("target_language", "—")}` |
| Note | {tr.get("note", "—")} |

**Translated Text:**
```
{tr.get("translated_text", "[No translation available]")}
```

---

## 📊 Quality Analysis

| Metric | Value | Grade |
|--------|-------|-------|
| Avg Segment Confidence | {q.get("avg_segment_confidence", "—")} | {q.get("quality_grade", "—")} |
| Word Error Rate (WER) | {wer_line} | {wer_grade} |
| Character Error Rate (CER) | {cer_line} | — |
| Flagged Segments | {q.get("flagged_low_confidence", 0)} / {q.get("total_segments", 0)} | — |

"""

    flagged = q.get("flagged_segments", [])
    if flagged:
        md += "### ⚠️ Low-Confidence Segments\n\n"
        md += "| Start | End | Text | Confidence |\n"
        md += "|-------|-----|------|------------|\n"
        for seg in flagged:
            md += f"| {seg['start']}s | {seg['end']}s | {seg['text'][:60]} | {seg['confidence']} |\n"
        md += "\n"
    else:
        md += "### ✅ No Low-Confidence Segments Detected\n\n"

    md += """---

## 🔬 Segment Detail

| # | Start | End | Text | Confidence |
|---|-------|-----|------|------------|
"""
    for seg in t.get("segments", []):
        confidence_emoji = "✅" if seg["confidence"] >= 0.75 else "⚠️"
        md += f"| {seg['id']} | {seg['start']}s | {seg['end']}s | {seg['text'][:50]} | {confidence_emoji} {seg['confidence']} |\n"

    md += """
---

## 💡 Recommendations

"""
    # Auto-generate basic recommendations
    avg_conf = q.get("avg_segment_confidence", 0)
    wer_val = q.get("wer")
    flagged_count = q.get("flagged_low_confidence", 0)
    total = q.get("total_segments", 1)

    if avg_conf < 0.75:
        md += "- 🔴 **Low average confidence** — consider re-collecting audio in controlled environment or using a larger Whisper model.\n"
    if wer_val is not None and wer_val > 0.15:
        md += "- 🟠 **High WER** — review transcription errors and augment training data with domain-specific vocabulary.\n"
    if flagged_count / max(total, 1) > 0.2:
        md += "- 🟡 **>20% segments flagged** — background noise or speaker overlap likely. Apply VAD pre-processing.\n"
    if avg_conf >= 0.85:
        md += "- 🟢 **High confidence** — transcription quality is good. Consider deploying to production.\n"
    if wer_val is not None and wer_val <= 0.05:
        md += "- 🟢 **WER ≤5%** — production-ready accuracy threshold achieved.\n"

    md += """
---

*Report generated by [Multilingual Indian ASR Intelligence Pipeline](https://github.com/rohitrajsingh)*
"""

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(md)
